all:
  children:
    transcriber:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python | default('/usr/bin/python3') }}"
